import { FaUserAlt } from "react-icons/fa";
import { FaLock } from "react-icons/fa";
import { FiArrowRight } from "react-icons/fi";
import { AiFillPlusCircle } from "react-icons/ai";
import { BiSearchAlt2 } from "react-icons/bi";
import { BiUpload } from "react-icons/bi";
import {BiShapePolygon} from "react-icons/bi";
import {MdOutlinePolyline} from "react-icons/md";
import {HiOutlineLocationMarker} from "react-icons/hi";
import {FiMousePointer} from "react-icons/fi";

export const UserAlt = FaUserAlt;
export const Lock = FaLock;
export const ArrowRight = FiArrowRight;
export const FillPlusCircle = AiFillPlusCircle;
export const SearchAlt2 = BiSearchAlt2;
export const Upload = BiUpload;
export const ShapePolygon = BiShapePolygon;
export const OutlinePolyline = MdOutlinePolyline;
export const OutlineLocationMarker = HiOutlineLocationMarker;
export const MousePointer = FiMousePointer;